// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BuildPlanFromBatch(arg1:string,arg2:Array<string>,arg3:main.BatchParams):Promise<main.PlanResult>;

export function BuildPlanFromPairs(arg1:string,arg2:Record<string, string>):Promise<main.PlanResult>;

export function ExecuteRename(arg1:Array<main.RenameOp>):Promise<main.ExecuteResult>;

export function GetFilesInDirectory(arg1:string):Promise<Array<main.FileInfo>>;

export function SelectFolder(arg1:string):Promise<string>;

export function WindowClose():Promise<void>;

export function WindowMinimize():Promise<void>;

export function WindowToggleMaximize():Promise<void>;
