// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildPlanFromBatch(arg1, arg2, arg3) {
  return window['go']['main']['App']['BuildPlanFromBatch'](arg1, arg2, arg3);
}

export function BuildPlanFromPairs(arg1, arg2) {
  return window['go']['main']['App']['BuildPlanFromPairs'](arg1, arg2);
}

export function ExecuteRename(arg1) {
  return window['go']['main']['App']['ExecuteRename'](arg1);
}

export function GetFilesInDirectory(arg1) {
  return window['go']['main']['App']['GetFilesInDirectory'](arg1);
}

export function SelectFolder(arg1) {
  return window['go']['main']['App']['SelectFolder'](arg1);
}

export function WindowClose() {
  return window['go']['main']['App']['WindowClose']();
}

export function WindowMinimize() {
  return window['go']['main']['App']['WindowMinimize']();
}

export function WindowToggleMaximize() {
  return window['go']['main']['App']['WindowToggleMaximize']();
}
